const express=require('express')
const app=express()
const bp=require('body-parser')
const cors=require('cors')
app.use(cors({origin:'http://localhost:3000',credentials:true}))
app.use(bp.json())
const cookie=require('cookie-parser')
app.use(cookie())
const usermodel=require('./UserModel')
const signup=require('./SignUp')
const signin=require('./SignIn')
const protected=require('./Router')
app.use('/',signup)
app.use('/',signin)
app.use('/',protected)
app.listen(3001,()=>console.log('server started'))